media:
  input: collections/images
  output: /collections/images
  path: collections/images
  categories: [image, video]
content:
  - name: homepage
    label: Home page
    type: file
    path: index.markdown
  - name: posts
    label: Posts
    type: collection
    path: collections/_posts
    subfolders: false
    view:
      fields: [ title, date, author ]
      sort: [ date, title, author ]
    fields:
      - name: layout
        type: string
        default: review
        hidden: true
      - name: date
        type: date
        hidden: true
      - name: title
        label: Title of your post
        type: string
        required: true
      - name: tags
        label: Keywords
        type: string
        required: true
      - name: author
        label: Author of the post
        type: string
        required: true
      - name: cite
        label: Citation details
        type: object
        fields:
          - name: title
            label: Title of the paper
            type: text
            required: true
          - name: authors
            label: Authors of the paper
            type: string
            required: true
          - name: venue
            label: Name of the conference/journal
            type: string
            required: true
      - name: pdf
        label: Link to the open access pdf version
        type: string
        required: true
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: body
        label: Content of your post
        type: rich-text